export const datas = [
  {
    foto: '/assets/hasanduganpfp.png',
    url: 'hasan-dugan',
    isim: 'Hasan Dugan',
    hakkimda: "1974 Ankara doğumluyum. Öğrenim hayatımın tamamı Ankara'da geçti, 1998 yılında ODTÜ İstatistik Bölümünden mezun olduğumda kariyerim artık İstanbul'da devam ediyordu. 1998 de başlayan Bankacılık hayatım, Müfettiş, Şube Pazarlama, Bölge Pazarlama, Şube Müdürü olarak 17 yıl devam etti. Sonrasında özel sektörde, sektörün önde gelen firmalarında Finans Direktörlüğü, İç Denetim sorumlusu olarak çalıştım.  Ankara merkezli 212 Derece bünyesinde Koçluk eğitimleri alarak Koç unvanını aldım, Sermaye Piyasası Lisanslama Enstitüsü tarafından açılan Gayrimenkul Değerleme Lisansı eğitimi ve sınavlarını tamamlayarak Gayrimenkul Değerleme Uzmanı unvanını ve aynı zamanda Konkordato Komiserliği unvanını aldım. Emeklilik sonrası her zaman ilgimi çeken geçmişte şahsen alım satımlar yaptığım gayrimenkul sektöründe yola devam etme kararı aldım .  Kendi marka ve ofislerimizi oluşturduğum arkadaşlarım ile birlikte Ankara Çankaya Alacaatlı bölgesinde bulunan ofisimizde Gayrimenkul Danışmanı olarak çalışmaya devam etmekteyim. ",
    telefon: '+90 532 485 2602',
    mail: 'hdugan@gmail.com',
    instagram: 'https://instagram.com/hasandugangd',
    whatsapp: 'https://wa.me/905324852602',
    endeksa: 'https://www.endeksa.com/tr/danisman/hasan-dugan/d6c1a6c9-03a3-4efb-bd1c-3a7e4dd26133',
    properties: [
      {
        id: '1',
        imageURL: 'https://i0.shbdn.com/photos/87/45/37/1257874537mre.jpg',
        title: 'YDA MEHMET AKİF ERSOY KONUTLARI 3+1 Kiralık 11. Kat',
        price: 35100,
        location: 'Ankara Yenimahalle',
        emlakci: 'Hasan Dugan',
        durum: 'Kiralık',
        konumLinki: 'https://www.google.com/maps/dir//39.9678333,32.7700998/@39.9415995,32.7271623,12z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Ankara’nın gözde projelerinden YDA Mehmet Akif Ersoy Konutları’nda, 11. katta konumlanan bu şık 3+1 daire, modern yaşamın tüm ayrıcalıklarını sunuyor.\nKuzeybatı cepheye konumuyla gün boyu dengeli bir ışık alan daire, Aselsan fabrikası ve şehrin dinamik manzarasına hakim bir perspektif sunuyor.\nGeniş ve ferah iç mekanlarıyla dikkat çeken bu daire, aileler ve çalışan profesyoneller için ideal bir yaşam alanı vaat ediyor.\nMacunköy Metro Durağı’na yürüme mesafesinde olması sayesinde ulaşım sorununu ortadan kaldıran bu daire, şehrin önemli noktalarına kolayca erişim imkanı sağlıyor.\nAynı zamanda yakın konumdaki AVM ile alışveriş, yeme-içme ve sosyal ihtiyaçlarınızı rahatlıkla karşılayabilirsiniz.\nProjenin güvenli ve sakin ortamı, çocuklu aileler için de büyük bir avantaj sunuyor.\nYDA Mehmet Akif Ersoy Konutları’nın kaliteli yaşam standartlarına uygun olarak tasarlanan bu daire, fonksiyonel bölümleri ve şık mimarisiyle dikkat çekiyor.\nDiğer dairelerden farkı olan balkonuyla keyifli vakit geçirebileceğiniz bir alan sunuluyor.\nEğer şehrin merkezinde, hem sakin hem de her imkana yakın bir yaşam arıyorsanız, bu daire tam size göre!',
        m2: 120,
        odaSayisi: '3+1',
        ilanTarihi: '2025-07-19', // Varsayılan değer
        emlakTipi: 'Kiralık Daire',
        binaYasi: 0, // Varsayılan değer
        bulunduguKat: '11. Kat', // Açıklamadan çıkarıldı
        katSayisi: 15, // Tahmini değer
        isitma: 'Kombi Doğalgaz', // Açıklamadan çıkarıldı
        banyoSayisi: '2', // Tahmini değer
        mutfakTipi: 'Açık', // Tahmini değer
        balkon: 'Var (Kapalı)', // Açıklamadan çıkarıldı
        asansor: 'Var', // Tahmini değer
        otopark: 'Var', // Tahmini değer
        esyali: 'Hayır',
        kullanimDurumu: 'Boş', // Tahmini değer
        siteIcerisinde: 'Var', // Açıklamadan çıkarıldı
        krediyeUygun: 'Uygun', // Açıklamadan çıkarıldı
        tapuDurumu: 'Kat Mülkiyetli', // Tahmini değer
        kimden: 'Emlakçıdan', // Açıklamadan çıkarıldı
        takas: 'Hayır',
      },
      {
        id: '2',
        imageURL: 'https://i0.shbdn.com/photos/15/46/55/12571546551bj.jpg',
        title: 'Kazan Yeşilova Villalarında Bağımsız Köşe Lüks Tripleks Villa',
        price: 10000000,
        location: 'Ankara Kahramankazan',
        emlakci: 'Hasan Dugan',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//40.1843859,32.6879245/@40.0552261,32.556688,11z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Kazan\'ın prestijli ve doğayla iç içe konumuyla öne çıkan Yeşilova Kent Villaları\'nda, az sayıda bulunan bağımsız villamız satışa sunulmuştur.\nModern mimarisi, geniş yeşil alanları ve sakin ortamıyla dikkat çeken bu villa, aradığınız özel yaşam alanını sunuyor.\n3 katlı ayrıca depo alanı da bulunan Villamızda 4+1 2 Banyo ve 3 adet WC^ye sahiptir.\nGeniş bahçesi ve yetişmiş meyve ağaçları ile bahçesinde bulunan çocuk parkı ile size şehir karmaşasından uzak bir hayat sunuyor.\nMarket ve Alışveriş bölgesine 150 mt.\nDetaylı bilgi ve randevu için lütfen iletişime geçiniz.',
        m2: 300,
        odaSayisi: '4+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Villa',
        binaYasi: 5, // Tahmini değer
        bulunduguKat: 'Tripleks',
        katSayisi: 3,
        isitma: 'Kombi Doğalgaz', // Tahmini değer
        banyoSayisi: '2', // Açıklamadan çıkarıldı
        mutfakTipi: 'Kapalı', // Tahmini değer
        balkon: 'Var',
        asansor: 'Yok',
        otopark: 'Açık Otopark',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Müstakil Tapu', // Tahmini değer
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '3',
        imageURL: 'https://i0.shbdn.com/photos/05/30/79/1245053079t6o.jpg',
        title: 'Ankara Gölbaşı - Gerder Mahallesi Satılık Arsa Hissesi',
        price: 7500000,
        location: 'Ankara Gölbaşı',
        emlakci: 'Hasan Dugan',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.7507143,32.867074/@39.8395243,32.7515268,12z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: '8.432 M2 lik arsamız 3 hissedara ait olup 1 hisse satılmaktadır.\nAnkara\'nın gelecek vaadeden bölgesinde erken yatırım fırsatı.\nDoğalgaz ve Elektrik hattı hazır bölgede.\nGölbaşı Gerder TOKI Projesine (@golbasi.gerder.toki) yakın.\nAnkara’nın ulaşım master planında Gölbaşı’na metro entegrasyonu gündemde olup, bu projenin hayata geçmesi durumunda bölge değeri hızla artacaktır.\nKonut, sosyal tesis veya yatırım amaçlı projeler için ideal.\nTOKİ ve özel sektör tarafından planlanan yeni konut projeleri ile bölgenin değeri hızla artmakta.\nParsel, imar planlarına doğrultusunda konut veya ticari projeler için uygun.\nYeni altyapı çalışmaları ve kamu yatırımları ile bölge cazibesini artırmaktadır.',
        m2: 2700,
        odaSayisi: '-',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Arsa',
        binaYasi: null, // Arsa olduğu için
        bulunduguKat: null, // Arsa olduğu için
        katSayisi: null, // Arsa olduğu için
        isitma: null, // Arsa olduğu için
        banyoSayisi: null, // Arsa olduğu için
        mutfakTipi: null, // Arsa olduğu için
        balkon: 'Yok',
        asansor: 'Yok',
        otopark: 'Yok',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Yok',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Hisseli Tapu', // Açıklamadan çıkarıldı
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '4',
        imageURL: 'https://i0.shbdn.com/photos/83/42/18/1249834218wis.jpg',
        title: 'PENTA NEST Güvencesi ile ERGAZİ ÖZDAMLA SİTESİ SATILIK 3+1 Daire',
        price: 4390000,
        location: 'Ankara Yenimahalle',
        emlakci: 'Hasan Dugan',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.9577395,32.7135194/@39.9408507,32.6942884,12z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'YENİLENMİŞ LÜKS 3+1 DAİRE - ÖZDAMLA SİTESİ / ERGAZİ MAHALLESİ.\nKöşe Daire - 2 Balkonlu (Kapalı) - Krediye Uygun - Şehir Merkezine Yakın.\nÖzdamla Sitesi, Ergazi Mahallesi, Yenimahalle / Ankara.\n25 Dönüm yeşil alan içinde 28 bloktan oluşan bakımlı ve güvenli site.\n5 katlı, 5. katta köşe daire (güneş alan, ferah).\nKök tapulu, krediye uygun (Kredi işlemleriniz eski bankacılardan oluşan Penta Nest ekibi tarafından yönetilir).\nOda Sayısı: 3+1 (geniş ve modern tasarım).\n2 adet kapalı balkon (manzaralı).\nTamamen yenilenmiş.\nKombi doğalgaz.\nŞifreli/çipli anahtar giriş sistemi (site ve bina girişleri kontrollü).\nSite içi Peyzaj alanlarına ilave Asaf Bey Parkı (hemen bitişiğinde).\nAtlantis AVM, Migros, BİM, semt pazarı.\nErgazi Aile Sağlık Merkezi, Yenimahalle Devlet Hastanesi.\nMetro (Batıkent hattı Anıt Durağı), otobüs durakları, minibüs hatları.\nErgazi İlkokulu, özel kreşler.\nŞehir karmaşasından uzak, ulaşımı kolay, sessiz, yeşil ve güvenli bir ortamda yer alan bu Mülk sahibinin ikamet ettiği dairemizi görmek için lütfen iletişime geçiniz.',
        m2: 125,
        odaSayisi: '3+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Daire',
        binaYasi: 0, // Tahmini değer (Yenilenmiş)
        bulunduguKat: '5. Kat',
        katSayisi: 5,
        isitma: 'Kombi Doğalgaz',
        banyoSayisi: '1', // Tahmini değer
        mutfakTipi: 'Kapalı', // Tahmini değer
        balkon: 'Var (2 adet kapalı)',
        asansor: 'Var',
        otopark: 'Var',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş', // "Mülk sahibinin ikamet ettiği" -> boş
        siteIcerisinde: 'Var',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kök Tapulu', // Açıklamadan çıkarıldı
        kimden: 'Sahibinden', // "Mülk sahibinin ikamet ettiği"
        takas: 'Hayır',
      },
      {
        id: '5',
        imageURL: 'https://i0.shbdn.com/photos/05/04/14/x5_12560504148gh.jpg',
        title: 'Penta Nest Güvencesiyle Pursaklar Fatih Mah. Satılık 3+1 Daire',
        price: 2990000,
        location: 'Ankara Pursaklar',
        emlakci: 'Hasan Dugan',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//40.0408456,32.8989339/@39.9805334,32.7894961,12z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Pursaklar\'da Köşe Başı 3+1 Daire - SATILIK.\nBodrum Sokak No:18, 1. Kat 120 m².\nCaddeye bakan köşe konumuyla tüm gün güneş alır, aydınlık ve ferah bir yaşam sunar.\nGömme dolaplarıyla pratik kullanım, kiracılı ve bakımlı durumda.\nUlaşım, sağlık ve eğitim imkanlarına yürüme mesafesinde!\nOtobüs Durağı: 439-440 numaralı hatlara yürüme mesafesi.\nPursaklar Devlet Hastanesi → 1.2 km.\nA Life Hastanesi → Yürüme mesafesi.\nFatih & Saray Aile Sağlık Merkezi → 500 m.\nŞehit Ali Yıldırım Ortaokulu → 400 m.\nPursaklar İMKB Meslek Lisesi → 700 m.\nGros market, Pursaklar Salı Pazarı → 1.5 km.\nFatih Camii → 200 m.\nOyun parkı & yürüyüş yolu → Binanın hemen arkasında!\nProtokol yoluna 10 dakika.\nBelediye, Emniyet Müdürlüğü, Kaymakamlık → 1.5 km çevrede.',
        m2: 130,
        odaSayisi: '3+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Daire',
        binaYasi: 10, // Tahmini değer
        bulunduguKat: '1. Kat',
        katSayisi: 5, // Tahmini değer
        isitma: 'Kombi Doğalgaz', // Tahmini değer
        banyoSayisi: '1', // Tahmini değer
        mutfakTipi: 'Kapalı', // Tahmini değer
        balkon: 'Var',
        asansor: 'Var', // Tahmini değer
        otopark: 'Açık Otopark', // Tahmini değer
        esyali: 'Hayır',
        kullanimDurumu: 'Kiracılı', // Açıklamadan çıkarıldı
        siteIcerisinde: 'Yok', // Tahmini değer
        krediyeUygun: 'Uygun', // Tahmini değer
        tapuDurumu: 'Kat Mülkiyetli', // Tahmini değer
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '6',
        imageURL: 'https://i0.shbdn.com/photos/02/14/45/x5_12560214451ve.jpg',
        title: 'Kızılay Atatürk Bulvarı Engürü Pasajı Satılık İşyeri',
        price: 1250000,
        location: 'Ankara Çankaya',
        emlakci: 'Hasan Dugan',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.9186982,32.8545981/@39.9208509,32.8376234,15z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Ankara Kızılay\'ın Kalbinde İşletme Fırsatı!\nKızılay, Atatürk Blv No:107/ 14. 8 m² (2,30 Mt cephesi bulunmaktadır.) (Pasaj alt katında).\nAnkara’nın en işlek noktası, Kızılay’ın tam göbeğinde!\nGün boyu yoğun insan trafiği ile ticaretin merkezinde.\nKızılay Metro, otobüs durakları ve yaya akışıyla günde 100.000 kişi üzerinde yaya trafiği.\nDüşük maliyetle işletme kurma veya yatırım yapma fırsatı.\nFırsatı kaçırmayın, Kızılay’da ticaretin tam ortasında yerinizi alın!\nGayrimenkulün satışında tek yetkili Penta Nest Gayrimenkul Ofisidir.\nDetaylı bilgi ve randevu için lütfen iletişime geçiniz.',
        m2: 8,
        odaSayisi: '-',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık İşyeri',
        binaYasi: 40, // Tahmini değer
        bulunduguKat: 'Alt Kat', // Açıklamadan çıkarıldı
        katSayisi: 5, // Tahmini değer
        isitma: 'Merkezi', // Tahmini değer
        banyoSayisi: '-',
        mutfakTipi: '-',
        balkon: 'Yok',
        asansor: 'Var', // Tahmini değer
        otopark: 'Yok',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş', // Tahmini değer
        siteIcerisinde: 'Var (Pasaj)', // Açıklamadan çıkarıldı
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli', // Tahmini değer
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '7',
        imageURL: 'https://i0.shbdn.com/photos/65/69/52/x5_125465695299l.jpg',
        title: 'Çankaya Karataş Ballı Pınar Satılık Hisseli Tarla 1.4 Dönüm',
        price: 1000000,
        location: 'Ankara Çankaya',
        emlakci: 'Hasan Dugan',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.8157157,32.9000801/@39.8720143,32.7697924,12z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Ankara Çankaya Karataş Mahallesi Ballıpınar Mevkiinde tamamı 11 Dönüm olan Tarlamızın 5/40 oranında hissesine denk gelen 1.387 M2 lik kısmı satılıktır.\n123 Ada 75 Parselde yer alan Tarlamız % 40 Eğime sahiptir.\nAnkara Konya Devlet Yoluna 9.600 Metre Uzaklıktadır.\nKaraoğlan 9 Km, Örencik 7 Km, Yurtbeyi ne 6 Km, Yaylabağ 3 Km mesafede yer almaktadır.',
        m2: 1400,
        odaSayisi: '-',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Tarla',
        binaYasi: null,
        bulunduguKat: null,
        katSayisi: null,
        isitma: null,
        banyoSayisi: null,
        mutfakTipi: null,
        balkon: 'Yok',
        asansor: 'Yok',
        otopark: 'Yok',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Yok',
        krediyeUygun: 'Uygun Değil', // Tahmini değer
        tapuDurumu: 'Hisseli Tapu',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '8',
        imageURL: 'https://i0.shbdn.com/photos/11/60/27/x5_1253116027d87.jpg',
        title: 'SÜPER LÜKS KONUT',
        price: 8100000,
        location: 'Ankara Mamak',
        emlakci: 'Hasan Dugan',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.910987,32.9104243/@39.9204616,32.8371436,13z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Yeni Rezidansınız Ağustos 2025\'te Hazır! Hem Konforlu Yaşam Hem Profesyonel Çalışma Alanı.\nŞehrin kalbinde yükselen bu modern rezidans, Ağustos 2025\'te oturuma hazır hale gelecek.\nHem konut hem de işyeri olarak kullanabileceğiniz geniş ve fonksiyonel yaşam alanlarıyla, iş ve yaşam konforunu bir arada sunuyor.\nEşya fotoğrafları projenin temsili reklam fotoğrafları olup Kiracı ile Mülk sahibi ortak kararı doğrultusunda eşya konulacaktır.\n55m² brüt 45m² net alana sahip dairemiz Batı cepheli olup öğleden sonra güneşi almakta ve günbatımı manzaralıdır. C1 - 55.\n✔ Çift amaçlı kullanım: Daire veya ofis olarak kullanılabilir.\n✔ 7/24 güvenlik ile huzurlu bir ortam.\n✔ Her daireye özel kapalı otopark.\n✔ Yerden ısıtma sistemi ile konforlu yaşam.\n• Siemens 3\'lü ankastre set (modern mutfak donanımı).\n• Çamaşır makinesi dolabı.\n• Şık ve kullanışlı banyo ve WC tasarımı.\n• Korkuluk, vestiyer ve çelik kapı (güvenlik ve estetik).\n• Laminat ve parke zemin (şık ve dayanıklı).\n• Winsa PVC pencereler (ısı ve ses yalıtımlı).\n• 3 adet asansör.\n• Otobüs, minibüs durakları binanın hemen önünde.\n• Metro (Hastane Durağı) sadece 1.4 km uzaklıkta.\nÇEVREDEKİ ÖNEMLİ NOKTALAR.\n✔ Nazım Hikmet Kültür Merkezi → 50 metre.\n✔ Podium AVM → 750 metre.\n✔ Onkoloji Hastanesi → 1.5 km.\n✔ Yeni Adliye Sarayı (Eski MİT Yerleşkesi) → 2.1 km.\n✔ ASELSAN Genel Müdürlüğü → 2.2 km.\n✔ Acity AVM → 3 km.\n✔ Cumhurbaşkanlığı Külliyesi → 4.8 km.\n✔ Antares & Ankamall AVM → 4.8 - 5.5 km.\n✔ Etlik & Bilkent Şehir Hastaneleri → 5.7 - 11 km.',
        m2: 220,
        odaSayisi: '4.5+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Konut',
        binaYasi: 0, // Yeni
        bulunduguKat: 'Belirtilmemiş',
        katSayisi: 20, // Tahmini değer
        isitma: 'Yerden Isıtma',
        banyoSayisi: '2', // Tahmini değer
        mutfakTipi: 'Açık', // Tahmini değer
        balkon: 'Yok',
        asansor: 'Var (3 adet)',
        otopark: 'Kapalı Otopark',
        esyali: 'Kısmen Eşyalı', // Açıklamadan çıkarıldı
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var (Rezidans)',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '9',
        imageURL: 'https://i0.shbdn.com/photos/12/04/80/x5_125312048043b.jpg',
        title: 'Yakupabdal da Satılık Hisseli Tarla 1.375 m2',
        price: 2800000,
        location: 'Ankara Çankaya',
        emlakci: 'Hasan Dugan',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.80712,32.9559621/@39.8701884,32.8187746,12z?entry=ttu&g_ep=EgoyMDI1MDcxMy4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Yeni Rezidansınız Ağustos 2025\'te Hazır! Hem Konforlu Yaşam Hem Profesyonel Çalışma Alanı.\nŞehrin kalbinde yükselen bu modern rezidans, Ağustos 2025\'te oturuma hazır hale gelecek.\nHem konut hem de işyeri olarak kullanabileceğiniz geniş ve fonksiyonel yaşam alanlarıyla, iş ve yaşam konforunu bir arada sunuyor.\n55m² brüt 45m² net alana sahip dairemiz Batı cepheli olup öğleden sonra güneşi almakta ve günbatımı manzaralıdır. B2 - 78.\n✔ Çift amaçlı kullanım: Daire veya ofis olarak kullanılabilir.\n✔ 7/24 güvenlik ile huzurlu bir ortam.\n✔ Her daireye özel kapalı otopark.\n✔ Yerden ısıtma sistemi ile konforlu yaşam.\n• Siemens 3\'lü ankastre set (modern mutfak donanımı).\n• Çamaşır makinesi dolabı.\n• Şık ve kullanışlı banyo ve WC tasarımı.\n• Korkuluk, vestiyer ve çelik kapı (güvenlik ve estetik).\n• Laminat ve parke zemin (şık ve dayanıklı).\n• Winsa PVC pencereler (ısı ve ses yalıtımlı).\n• 3 adet asansör.\n• Otobüs, minibüs durakları binanın hemen önünde.\n• Metro (Hastane Durağı) sadece 1.4 km uzaklıkta.\nÇEVREDEKİ ÖNEMLİ NOKTALAR.\n✔ Nazım Hikmet Kültür Merkezi → 50 metre.\n✔ Podium AVM → 750 metre.\n✔ Onkoloji Hastanesi → 1.5 km.\n✔ Yeni Adliye Sarayı (Eski MİT Yerleşkesi) → 2.1 km.\n✔ ASELSAN Genel Müdürlüğü → 2.2 km.\n✔ Acity AVM → 3 km.\n✔ Cumhurbaşkanlığı Külliyesi → 4.8 km.\n✔ Antares & Ankamall AVM → 4.8 - 5.5 km.\n✔ Etlik & Bilkent Şehir Hastaneleri → 5.7 - 11 km.',
        m2: 1375,
        odaSayisi: '-',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Tarla',
        binaYasi: null,
        bulunduguKat: null,
        katSayisi: null,
        isitma: null,
        banyoSayisi: null,
        mutfakTipi: null,
        balkon: 'Yok',
        asansor: 'Yok',
        otopark: 'Yok',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Yok',
        krediyeUygun: 'Uygun Değil', // Tarla için tahmini
        tapuDurumu: 'Hisseli Tapu',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '10',
        imageURL: 'https://i0.shbdn.com/photos/29/70/35/1259297035tka.jpg',
        title: 'Kiralık Ofis Daire İpektaş Cadde 1+1 55m², Merkezi Adliye Yakını',
        price: 39000,
        location: 'Ankara Yenimahalle',
        emlakci: 'Hasan Dugan', // Emlakçı burada Hasan Dugan görünüyor
        durum: 'Kiralık',
        konumLinki: 'https://www.google.com/maps/dir//39.9598836,32.7777356/@39.9023307,32.6466085,12z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: '', // Bu açıklama boş bırakılmış, önceki isteğinizde Şerife Çelik'in ofis açıklaması vardı.
        m2: 55,
        odaSayisi: '1+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Kiralık Ofis',
        binaYasi: 0, // Tahmini değer
        bulunduguKat: 'Belirtilmemiş',
        katSayisi: 10, // Tahmini değer
        isitma: 'Merkezi',
        banyoSayisi: '1',
        mutfakTipi: 'Amerikan', // Tahmini değer
        balkon: 'Yok',
        asansor: 'Var',
        otopark: 'Var',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Yok',
        krediyeUygun: 'Belirtilmemiş',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '11',
        imageURL: 'https://i0.shbdn.com/photos/10/04/07/x5_12591004077yp.jpg',
        title: 'Kiralık Ofis Daire EŞYALI İpektaş Cadde 1+1 55m² Adliye Yakını',
        price: 35000,
        location: 'Ankara Yenimahalle',
        emlakci: 'Hasan Dugan',
        durum: 'Kiralık',
        konumLinki: 'https://www.google.com/maps/dir//39.9598964,32.7775857/@39.9020676,32.6466085,12z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: '', // Bu açıklama boş bırakılmış
        m2: 55,
        odaSayisi: '1+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Kiralık Ofis',
        binaYasi: 0,
        bulunduguKat: 'Belirtilmemiş',
        katSayisi: 10,
        isitma: 'Merkezi',
        banyoSayisi: '1',
        mutfakTipi: 'Amerikan',
        balkon: 'Yok',
        asansor: 'Var',
        otopark: 'Var',
        esyali: 'Var', // Eşyalı
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Yok',
        krediyeUygun: 'Belirtilmemiş',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '12',
        imageURL: 'https://i0.shbdn.com/photos/71/79/03/lthmb_12597179037fz.jpg',
        title: 'Nev201 Yüksek Kat Şehir Manzaralı 88 m² Full Yapılı Ofis Kiralık',
        price: 80000,
        location: 'Ankara Çankaya',
        emlakci: 'Hasan Dugan',
        durum: 'Kiralık',
        konumLinki: 'https://www.google.com/maps/dir//39.8884656,32.8136283/@39.8766324,32.8081727,15z?entry=ttu&g_ep=EgoyMDI1MDcxNi4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Nev201’de Prestijli, Stratejik ve yapılı şık 88 m² Ofis Fırsatı.\nAnkara’nın iş ve yaşam merkezi Mevlana Bulvarı üzerinde konumlanan Nev201, Kalyon İnşaat ve Asfuroğlu Grubu iş birliğiyle hayata geçirilmiş, ünlü mimar Emre Arolat imzası taşıyan modern ve prestijli bir projedir.\n239 Ofis ve 35 Ticari ünitesi bulunmaktadır.\nAyrıca yüksek hızlı 6 adet Kone Marka Asansörü bulunmaktadır.\n17.katta yer alan ofisimiz, şık ve modern bir şekilde dizayn edilmiş 88 m² net kullanım alanı ve panoramik şehir manzarasıyla ferah, bol ışık alan bir çalışma ortamı sunar.\Gelişmiş DAIKIN VRV IV+ Geri Kazanımlı Isı Pompası sistemi sayesinde yüksek verimli ve konforlu iklimlendirme sağlanırken, ofiste yer alan mutfak alanı ve ortak kullanım WC’leriyle fonksiyonellik ön planda tutulmuştur.\nÖne Çıkan Özellikler:\n* 1.274 araç kapasiteli kapalı otopark.\n* 7/24 güvenlik hizmeti.\n* Fiber internet altyapısı.\n* Her katta ortak kullanıma açık balkonlar.\n* Merkezi konum ve ulaşım kolaylığı.\nKamu İhale Kurumu, Taurus AVM, Koru Hastanesi, Memorial Hastanesi, Next Level, Armada AVM ve ODTÜ gibi önemli noktalara yakınlığı sayesinde hem prestijli hem de stratejik bir lokasyonda yer alan bu özel ofisi kaçırmayın!',
        m2: 95,
        odaSayisi: '3+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Kiralık Ofis',
        binaYasi: 0, // Yeni bina
        bulunduguKat: '17. Kat',
        katSayisi: 20, // Tahmini değer
        isitma: 'DAIKIN VRV IV+ Geri Kazanımlı Isı Pompası',
        banyoSayisi: 'Ortak WC', // Açıklamadan çıkarıldı
        mutfakTipi: 'Mutfak Alanı Mevcut',
        balkon: 'Var (Her katta ortak)',
        asansor: 'Var (6 adet Kone)',
        otopark: 'Kapalı Otopark',
        esyali: 'Hayır', // Full yapılı ama eşyalı değil
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var (Plaza)',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli', // Tahmini değer
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
    ],
  },
  {
    foto: '/assets/serifecelikpfp.png',
    isim: 'Şerife Çelik',
    url: "serife-celik",
    hakkimda: "Emlak uzmanıyım",
    telefon: '+90 532 549 47 49',
    mail: 'serifecelik@gmail.com',
    instagram: 'https://instagram.com/serifedilercelik1',
    whatsapp: 'https://wa.me/905325494749',
    endeksa: 'https://www.endeksa.com/tr/danisman/serife-celik/00f1dab4-3331-4000-b615-2ba1240609b9',
    properties: [
      {
        id: '1',
        imageURL: 'https://i0.shbdn.com/photos/80/83/68/x5_1245808368eea.jpg',
        title: 'OFİS 110 PLAZA DIŞKAPI METRO DURAĞINDA KİRALIK 145 M2 OFİS',
        price: 60000,
        location: 'Ankara Altındağ',
        emlakci: 'Şerife Çelik',
        durum: 'Kiralık',
        konumLinki: 'https://www.google.com/maps/dir//39.9559854,32.8583274/@39.9559781,32.8171279,13z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: 'OFİS 110 PLAZA KİRALIK OFİS.\nDışkapı Metro çıkışında olup, Plazada 85 Ofis, İtfaiye Çarşısında 152 Dükkan bulunmaktadır.\n60 Ofis 1+0, 15 Ofis 2+0, 10 Ofis 3+0 Ofisten oluşmaktadır.\nGENEL ÖZELLİKLER:\n4. Kat, 145 m2 Net Kullanım Alanı, Şehir Manzaralı, Fancoil Isıtma Sistemi, Laminant ve Islak Zemin Seramik, Yangın Söndürme Sistemi, 2 Asansör, Ofis Girişi Bağımsız, Açık ve Kapalı Otopark, 6 Dönüm Peyzaj Alanı, Kamelyalar, Çocuk Bahçesi, 24 Saat Güvenlik, 265 Adet Kayıtlı Kamera Sistemi.\nAnkara Üniversitesi Ziraat Fakültesi, Dışkapı Yıldırım Beyazıt Eğitim ve Araştırma Hastanesi, Gülhane Eğitim ve Araştırma Hastanesi, Türk Telekom Genel Müdürlüğü, Aski Genel Müdürlüğüne yakın konumda bulunmaktadır.\nDETAYLI BİLGİ İÇİN LÜTFEN ARAYIN.',
        m2: 145,
        odaSayisi: '3+0',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Kiralık Ofis',
        binaYasi: 0,
        bulunduguKat: '4. Kat',
        katSayisi: 10, // Tahmini değer
        isitma: 'Fancoil Isıtma Sistemi',
        banyoSayisi: 'Ortak WC', // Tahmini değer
        mutfakTipi: 'Yok', // Tahmini değer
        balkon: 'Yok',
        asansor: 'Var (2 Adet)',
        otopark: 'Açık ve Kapalı Otopark',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş', // Tahmini değer
        siteIcerisinde: 'Var (Plaza)',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '2',
        imageURL: 'https://i0.shbdn.com/photos/95/67/11/1247956711s7b.jpg',
        title: 'AKADİA MODERN KONUTLARINDA BOŞ 2+1 TEMİZ YAPILI SATILIK DAİRE',
        price: 6400000,
        location: 'Ankara Mamak',
        emlakci: 'Şerife Çelik',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.8898253,32.9326293/@39.8389139,32.6453055,11z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: 'GENEL ÖZELLİKLERİ:\nDoğukent Bulvarına Cephe, Ikea ve Nata Vega AVM Karşısında Akadia Modern Konutlarında.\nArsa Alanı 50000 m2.\n891 Konut 2+1 3+1 4+1.\n8 Katlı Bina, 4. Kat.\nTip 10. 105 m2 Net Kullanım Alanı.\n7/24 Güvenlik, Kamera Sistemleri.\nMerkezi (Pay Ölçer) Isıtma.\nKapalı ve Açık Otopark.\nAnkastre Set (Fırın, Mikrodalga Fırın, Ocak, Davlumbaz).\nDuvar Kağıdı.\nMutfak Kapısı Sürgülü.\nÇelik Kapı.\nYangın Uyarı Sistemi.\nMerkezi Uydu Sistemi.\nGiyinme Odası.\nEbeveyn Banyosu.\nDairemiz Temiz ve Yapılıdır.\nÇocuk Parkı.\nPeyzaj Alanı.\nHamam, Sauna, Buhar Odası.\nDairemiz Lokasyon olarak Otobüs ve Dolmuş Duraklarına Yakın, Nata Vega AVM, Metro Market ve İkea\'ya yürüme mesafesinde, Bim, A101 ve Şok Marketlerine Yürüme Mesafesinde, Çevre Yoluna Yakın Bulunmaktadır.\nDETAYLI BİLGİ İÇİN LÜTFEN ARAYINIZ...',
        m2: 119,
        odaSayisi: '2+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Daire',
        binaYasi: 0,
        bulunduguKat: '4. Kat',
        katSayisi: 8,
        isitma: 'Merkezi(Pay Ölçer)',
        banyoSayisi: '2', // Ebeveyn banyosu + normal
        mutfakTipi: 'Kapalı', // Mutfak kapısı sürgülü
        balkon: 'Var', // Tahmini değer
        asansor: 'Var',
        otopark: 'Kapalı ve Açık Otopark',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '3',
        imageURL: 'https://i0.shbdn.com/photos/10/51/17/x5_1235105117vo0.jpg',
        title: 'KUŞADASI/DAVUTLAR ORSEN SİT. DENİZE YAKIN EŞYALI SATILIK YAZLIK',
        price: 12900000,
        location: 'Aydın Kuşadası Davutlar',
        emlakci: 'Şerife Çelik',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//37.7697736,27.2635707/@38.6967504,24.6875355,6z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: 'Yazlığımız Kuşadası/Davutlar Mevkinde bulunmaktadır.\nOrsen Sitesi Denize Sıfır Konumdadır.\nGENEL ÖZELLİKLERİ:\nEşyalı, Köşe Villa, Geniş Bahçe, Çift Tapu.\n2 Ayrı Girişi Olduğundan 2 Ayrı Yazlık Olarak Kullanılabilir.\nHer Katta Mutfak ve Banyo.\nAlt Kat 1+1, Açık Mutfak.\nÜst Kat:1+1 Kapalı Mutfak.\nHer Katta Klima.\nGüneş Enerjisi.\nÇocuk Parkı.\nBahçe Bakımı.\nYazlığımız Denize Yürüme Mesafesi 5 Dk.\nSahil Boyunca Bisiklet ve Yürüyüş Yolları Bulunmaktadır.\nSite Konumu İtibariyle Marketlere, Ulaşım Araçlarına, Sosyal Alanlarına Yürüme Mesafesindedir.\nKuşadasına 20 Km Uzaklıktadır.\nDETAYLAR İÇİN LÜTFEN ARAYINIZ.\nDAİREYİ GÖRMEK İÇİN LÜTFEN RANDEVU ALINIZ.',
        m2: 150,
        odaSayisi: '3+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Yazlık',
        binaYasi: 20, // Tahmini değer
        bulunduguKat: 'Tripleks', // Tahmini değer
        katSayisi: 2, // 2 Ayrı Yazlık
        isitma: 'Klima',
        banyoSayisi: '2', // Her katta
        mutfakTipi: 'Açık/Kapalı', // Alt açık, üst kapalı
        balkon: 'Var', // Tahmini değer
        asansor: 'Yok',
        otopark: 'Açık Otopark', // Tahmini değer
        esyali: 'Var',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Çift Tapu',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '4',
        imageURL: 'https://i0.shbdn.com/photos/67/03/90/x5_123467039096t.jpg',
        title: 'OFİS 110 PLAZADA DIŞKAPI METRO ÇIKIŞI KİRALIK 60 M2 OFİS',
        price: 40000,
        location: 'Ankara Altındağ',
        emlakci: 'Şerife Çelik',
        durum: 'Kiralık',
        konumLinki: 'https://www.google.com/maps/dir//39.9559597,32.8587148/@39.9050852,32.6056394,11z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: 'OFİS 110 PLAZA.\nDışkapı Metro çıkışında olup, Plazada 85 Ofis, İtfaiye Çarşısında 152 Dükkan bulunmaktadır.\n60 Ofis 1+0, 15 Ofis 2+0, 10 Ofis 3+0 Ofisten oluşmaktadır.\nGENEL ÖZELLİKLER:\n6. Kat\n60 m2 Net Kullanım Alanı\nŞehir Manzaralı\nFancoil Isıtma Sistemi\nLaminant ve Islak Zemin Seramik\nYangın Söndürme Sistemi\n2 Asansör\nOfis Girişi Bağımsız\nAçık ve Kapalı Otopark\n6 Dönüm Peyzaj Alanı\nKamelyalar\nÇocuk Bahçesi\n24 Saat Güvenlik\n265 Adet Kayıtlı Kamera Sistemi.\nAnkara Üniversitesi Ziraat Fakültesi, Dışkapı Yıldırım Beyazıt Eğitim ve Araştırma Hastanesi, Gülhane Eğitim ve Araştırma Hastanesi, Türk Telekom Genel Müdürlüğü, Aski Genel Müdürlüğüne yakın konumda bulunmaktadır.\nDETAYLI BİLGİ İÇİN LÜTFEN ARAYIN.',
        m2: 60,
        odaSayisi: '2+0',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Kiralık Ofis',
        binaYasi: 0,
        bulunduguKat: '6. Kat',
        katSayisi: 10, // Tahmini değer
        isitma: 'Fancoil Isıtma Sistemi',
        banyoSayisi: 'Ortak WC', // Tahmini değer
        mutfakTipi: 'Yok',
        balkon: 'Yok',
        asansor: 'Var (2 Adet)',
        otopark: 'Açık ve Kapalı Otopark',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var (Plaza)',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '5',
        imageURL: 'https://i0.shbdn.com/photos/81/39/49/x5_1231813949hbn.jpg',
        title: 'ÇANKAYA ÖVEÇLER MAHALLESİ SATILIK 2 KATLI 230 M2 DÜKKAN',
        price: 69000000,
        location: 'Ankara Çankaya',
        emlakci: 'Şerife Çelik',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.893531,32.8263722/@39.87285,32.6698799,12z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: 'ÖVEÇLER\'DE ÇETİN EMEÇ CADDESİNE YAKIN SATILIK DÜKKAN.\nGenel Özellikleri:\nGiriş Kat, 230 m2 Net Kullanım Alanı.\nGiriş Kat 160 M2 - Alt Kat 70 M2.\nGiriş 2+1.\nAlt Kat Mutfak + WC + Açık Alan.\nAçık Otopark.\nDoğalgaz.\nKiracılı.\nDükkan Girişi Bağımsız.\nÇetin Emeç Bulvarına, Konya Yoluna, Balgat Semtine, Dikmen Caddesine, Polisevine, Emniyet Genel Müdürlüğüne yakın konumda bulunmaktadır.\nDETAYLI BİLGİ İÇİN LÜTFEN ARAYIN.',
        m2: 230,
        odaSayisi: '2+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Dükkan',
        binaYasi: 20, // Tahmini değer
        bulunduguKat: 'Giriş Kat',
        katSayisi: 2,
        isitma: 'Doğalgaz',
        banyoSayisi: '1',
        mutfakTipi: 'Var', // Alt katta mutfak var
        balkon: 'Yok',
        asansor: 'Yok',
        otopark: 'Açık Otopark',
        esyali: 'Hayır',
        kullanimDurumu: 'Kiracılı',
        siteIcerisinde: 'Yok',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '6',
        imageURL: 'https://i0.shbdn.com/photos/79/82/15/x5_1231798215htk.jpg',
        title: 'ÖVEÇLER MAH. ÇETİN EMEÇ BULVARINA YAKIN 170 M2 DÜKKAN',
        price: 6500000,
        location: 'Ankara Çankaya',
        emlakci: 'Şerife Çelik',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.8936535,32.8263168/@39.87285,32.6698522,12z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: 'ÖVEÇLER\'DE ÇETİN EMEÇ CADDESİNE YAKIN SATILIK DÜKKAN.\nGenel Özellikleri:\nGiriş Kat, 170 m2 Net Kullanım Alanı.\nGiriş Kat 100 M2 - Alt Kat 70 M2.\nGiriş 2+1.\nAlt Kat Mutfak + WC + Açık Alan.\nAçık Otopark.\nMerkezi Isıtma Sistemi.\nKiracılı.\nDükkan Girişi Bağımsız.\nÇetin Emeç Bulvarına, Konya Yoluna, Balgat Semtine, Dikmen Caddesine, Polisevine, Emniyet Genel Müdürlüğüne yakın konumda bulunmaktadır.\nDETAYLI BİLGİ İÇİN LÜTFEN ARAYIN.',
        m2: 170,
        odaSayisi: '2+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Dükkan',
        binaYasi: 20, // Tahmini değer
        bulunduguKat: 'Giriş Kat',
        katSayisi: 2,
        isitma: 'Merkezi Isıtma Sistemi',
        banyoSayisi: '1',
        mutfakTipi: 'Var',
        balkon: 'Yok',
        asansor: 'Yok',
        otopark: 'Açık Otopark',
        esyali: 'Hayır',
        kullanimDurumu: 'Kiracılı',
        siteIcerisinde: 'Yok',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '7',
        imageURL: 'https://i0.shbdn.com/photos/51/99/56/x5_12575199560yu.jpg',
        title: 'BİRLİK MAH. SATILIK 258 M2 DUBLEKS BAKIMLI 7+1 DAİRE',
        price: 9750000,
        location: 'Ankara Çankaya',
        emlakci: 'Şerife Çelik',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.8758797,32.877371/@39.8721982,32.6130105,11z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: 'GENEL ÖZELLİKLERİ:\nDubleks Bakımlı Daire.\n4 Katlı Bina, 3. Ve 4. Kat.\n6+1 (Teras kapatılmış olup, mutfak ve barbekü eklenmiştir. Oda olarak da kullanılabilir).\n258 m2 Net Kullanım Alanı.\nÇift Mutfak.\nÖn Cephe.\nGörüntülü Diyafon.\nKombi (Doğalgaz).\nAçık Otopark.\nAnkastre Set (Fırın, Mikrodalga Fırın, Ocak, Davlumbaz).\nÇelik Kapı.\Daireye Ait Depo.\nDairemiz Temiz ve Yapılıdır.\nDairemiz Lokasyon olarak Otobüs ve Dolmuş Duraklarına, Doğukent Bulvarı, 365 AVM, Lozan Parkı\'na yürüme mesafesinde, Marketlere, Okullara Yürüme Mesafesinde Bulunmaktadır.\nDETAYLI BİLGİ İÇİN LÜTFEN ARAYINIZ...',
        m2: 300,
        odaSayisi: '7+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Daire',
        binaYasi: 15, // Tahmini değer
        bulunduguKat: '3. ve 4. Kat',
        katSayisi: 4,
        isitma: 'Kombi Doğalgaz',
        banyoSayisi: '2', // Tahmini değer (Çift mutfak implies more baths)
        mutfakTipi: 'Çift Mutfak',
        balkon: 'Var (Teras kapatılmış)',
        asansor: 'Var', // Tahmini değer
        otopark: 'Açık Otopark',
        esyali: 'Hayır', // Bakımlı daire ama eşyalı değil
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Yok',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '8',
        imageURL: 'https://i0.shbdn.com/photos/78/78/53/x5_1231787853wtb.jpg',
        title: 'OFİS 110 PLAZA MANZARALI METRO GİRİŞİ SATILIK OFİS',
        price: 8850000,
        location: 'Ankara Altındağ',
        emlakci: 'Şerife Çelik',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//39.9578322,32.8577233/@39.9009825,32.6031477,11z?entry=ttu&g_ep=EgoyMDI1MDcxNS4xIKXMDSoASAFQAw%3D%3D',
        aciklama: 'DIŞKAPI İTFAİYE ÇARŞISI OFİS 110 SATILIK OFİS.\n6. Katta Ofisimiz Satılıktır.\nGenel Özellikleri:\n165 m2 Net Kullanım Alanı.\nFancoil Isıtma Sistemi.\nLaminant ve Islak Zemin Seramik.\nYangın Söndürme Sistemi.\n2 Asansör.\nOfis Girişi Bağımsız.\n24 Saat Güvenlik.\n265 Adet Kayıtlı Kamera Sistemi.\nAnkara Üniversitesi Ziraat Fakültesi, Dışkapı Yıldırım Beyazıt Eğitim ve Araştırma Hastanesi, Gülhane Eğitim ve Araştırma Hastanesi, Türk Telekom Genel Müdürlüğü, Aski Genel Müdürlüğüne yakın konumda bulunmaktadır.\nDETAYLI BİLGİ İÇİN LÜTFEN ARAYIN.\nİRTİBAT TELEFONLARIMIZ: ŞERİFE ÇELİK 0532 5494749, DUYGU GÜLNAZ 0532 4878126.',
        m2: 165,
        odaSayisi: '2+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Ofis',
        binaYasi: 0,
        bulunduguKat: '6. Kat',
        katSayisi: 10, // Tahmini değer
        isitma: 'Fancoil Isıtma Sistemi',
        banyoSayisi: 'Ortak WC',
        mutfakTipi: 'Yok',
        balkon: 'Yok',
        asansor: 'Var (2 Adet)',
        otopark: 'Var', // Tahmini değer
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var (Plaza)',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '9',
        imageURL: 'https://i0.shbdn.com/photos/60/96/45/x5_1238609645dcl.jpg',
        title: 'OFİS 110 PLAZADA METRO DURAĞINDA KİRALIK 60 M2 OFİS',
        price: 40000,
        location: 'Ankara Altındağ',
        emlakci: 'Şerife Çelik',
        durum: 'Kiralık',
        konumLinki: 'https://www.google.com/maps/dir//39.9558255,32.8586502/@39.9099518,32.7108447,12z?entry=ttu&g_ep=EgoyMDI1MDcyMC4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'OFİS 110 PLAZA\nDışkapı Metro çıkışında olup, Plazada 85 Ofis, İtfaiye Çarşısında 152 Dükkan bulunmaktadır.\n60 Ofis 1+0, 15 Ofis 2+0, 10 Ofis 3+0 Ofisten oluşmaktadır.\nGENEL ÖZELLİKLER\n4. Kat\n60 m2 Net Kullanım Alanı \nŞehir Manzaralı \nFancoil Isıtma Sistemi\nLaminant ve Islak Zemin Seramik\nYangın Söndürme Sistemi\n2 Asansör\nOfis Girişi Bağımsız\nAçık ve Kapalı Otopark\n6 Dönüm Peyzaj Alanı\nKamelyalar\nÇocuk Bahçesi\n24 Saat Güvenlik \n265 Adet Kayıtlı Kamera Sistemi\nAnkara Üniversitesi Ziraat Fakültesi, Dışkapı Yıldırım Beyazıt Eğitim ve Araştırma Hastanesi, Gülhane Eğitim ve Araştırma Hastanesi Türk Telekom Genel Müdürlüğü, Aski Genel Müdürlüğüne yakın konumda bulunmaktadır.\nDETAYLI BİLGİ İÇİN LÜTFEN ARAYIN.',
        m2: 60,
        odaSayisi: '2+0',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Kiralık Ofis',
        binaYasi: 0,
        bulunduguKat: '4. Kat',
        katSayisi: 10,
        isitma: 'Fancoil Isıtma Sistemi',
        banyoSayisi: 'Ortak WC',
        mutfakTipi: 'Yok',
        balkon: 'Yok',
        asansor: 'Var (2 Adet)',
        otopark: 'Açık ve Kapalı Otopark',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var (Plaza)',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
      {
        id: '10',
        imageURL: 'https://i0.shbdn.com/photos/95/04/48/x5_1231950448gs5.jpg',
        title: 'MALTEPE ZÜMRÜTEVLER TABLO ADALAR DA SATILIK 1+1 DAİRE',
        price: 7300000,
        location: 'Ankara Maltepe',
        emlakci: 'Şerife Çelik',
        durum: 'Satılık',
        konumLinki: 'https://www.google.com/maps/dir//40.9399851,29.1568693/@40.240996,28.3507636,7z?entry=ttu&g_ep=EgoyMDI1MDcyMC4wIKXMDSoASAFQAw%3D%3D',
        aciklama: 'TABLO ADALAR PROJESİ ; 15.000 m2 arazi üzerinde 2 Blok 316 Daireden oluşan bir alana sahiptir.\nProje prestijli sitelerin bulunduğu bir bölgede yeralmaktadır.\nGENEL ÖZELLİKLER\n64 M2 net 42 M2\nBalkon 6 M2\nOcak - Fırın - Bulaşık Makinası Sıemens Marka Ankastre\nDavlumbaz Teka Marka\nKapaklı Vestiyer\nÇamaşır Makinası Alanı\nKlima Alt Yapısı Hazır\nYerler Ahşap Parke Zemin\nMerkezi Isıtma Sistemi\nDaireye Ait Özel Depo\nÖzel Otopark Alanı\nAçık ve Kapalı Yüzme Havuz\nSauna - Fitness Salonu\nTenis Kortu , Basketbol Sahası\nÇocuk Oyun Alanları\nYürüyüş Yolları , Seyir Terası\n22 Adet Elektrikli Şarj İstasyonu\n24 Saat Canlı Güven\nEsenkent Metro Durağına 1 Dakika , E-5 Otoyolu 2 Dakika , Maltepe Park & Pizza AVM 2 Dakika\nAnatolium & Ikea AVM 4 Dakika, Maltepe Sahil 10 Dakika , Bostancı İdo 15 Dakika , 15 Temmuz Şehitler Köprüsü 20 Dakika ,\nSabiha Gökçen Havaalanı 20 Dakika , Avrasya Tüneli 25 Dakika mesafede bulunmaktadır\nDETAYLAR İÇİN LÜTFEN ARAYINIZ',
        m2: 64,
        odaSayisi: '1+1',
        ilanTarihi: '2025-07-19',
        emlakTipi: 'Satılık Daire',
        binaYasi: 0,
        bulunduguKat: 'Belirtilmemiş',
        katSayisi: 15, // Tahmini değer
        isitma: 'Merkezi Isıtma Sistemi',
        banyoSayisi: '1',
        mutfakTipi: 'Açık', // Tahmini
        balkon: 'Var (6 m2)',
        asansor: 'Var',
        otopark: 'Var',
        esyali: 'Hayır',
        kullanimDurumu: 'Boş',
        siteIcerisinde: 'Var',
        krediyeUygun: 'Uygun',
        tapuDurumu: 'Kat Mülkiyetli',
        kimden: 'Emlakçıdan',
        takas: 'Hayır',
      },
    ],
  },
];